### ISSUE TITLE
Zoom issue

### ISSUE THREAD

**Issue by zedeus** [can-lehmann/Graphing#2]
Scrolling out too far messes up the rendering and requires a ton of CPU resources, causing my computer to freeze.
![image](https://user-images.githubusercontent.com/9434921/220400950-5d89445a-5de3-4d1a-baf0-8f64b27647c9.png)

**Comment by can-lehmann** [comment]
Thanks for the report, this should be resolved in https://github.com/can-lehmann/Graphing/commit/03a55a819b65fc391c4b485dc13b640b4e023adb
