### ISSUE TITLE
Error undeclared WindowSurface

### ISSUE THREAD

**Issue by nimelias** [can-lehmann/Graphing#7]
Following install instructions gives me:
/tmp/nimble_370147/githubcom_canlehmannGraphing/src/graphing.nim(1214, 5) Error: undeclared identifier: 'WindowSurface'

I renamed to AdwWindow as stated in owlkettle's docs/migrating_2_to_3.md and goes well.
"The `WindowSurface` widget was renamed to `AdwWindow`."

You are doing an awesome job with Owlkettle!!!

**Comment by can-lehmann** [comment]
Thanks for reporting this issue, it should be fixed in https://github.com/can-lehmann/Graphing/commit/94b8b80df829c348c39fd990e2568a410f15ee02.
